[package]
name = "lab02_file_transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.5.4" }
local-ip-address = { version = "0.5.5" }
chrono = { version = "0.4.31" }
